include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    dead_code: error
    duplicate_import: error
    todo: ignore

linter:
  rules:
  - always_declare_return_types
  - avoid_relative_lib_imports
  - avoid_types_as_parameter_names
  - empty_statements
  - hash_and_equals
  - iterable_contains_unrelated_type
  - no_duplicate_case_values
  - unnecessary_statements
  - unrelated_type_equality_checks
  - always_put_required_named_parameters_first
  - avoid_classes_with_only_static_members
  - avoid_renaming_method_parameters
  - avoid_return_types_on_setters
  - constant_identifier_names
  - curly_braces_in_flow_control_structures
  - empty_catches
  - empty_constructor_bodies
  - file_names
  - implementation_imports
  - non_constant_identifier_names
  - parameter_assignments
  - prefer_conditional_assignment
  - prefer_const_constructors
  - prefer_equal_for_default_values
  - prefer_expression_function_bodies
  - prefer_final_locals
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_single_quotes
  - sort_unnamed_constructors_first
  - unnecessary_getters_setters
  - unnecessary_lambdas
  - unnecessary_this
  - camel_case_types
  - annotate_overrides
  - avoid_init_to_null
  - sort_constructors_first
  - avoid_empty_else
  - unnecessary_const
  - unnecessary_new